name: Sentinel

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-suite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
        spark-version: [3.1.1]
    steps:
    - uses: actions/checkout@v2
    - name: Run test suites
      run: |
        sudo chown -R 1000 .
        source ./build_image.sh
