name: Sentinel

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  install-checks:
    runs-on: ubuntu-latest
  test-suite:
    needs: install-checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test suites
      run: |
        source ./build_image.sh
